---
roles:
  - name: geerlingguy.apache
    version: 3.1.4
  - name: xanmanning.k3s
    version: v1.17.4
  # - name: geerlingguy.docker_arm
  #   version: 4.0.0
  # - name: geerlingguy.homebrew
  #   version: 3.1.0