---
# tasks file for myrole
- name: print the distribution and version
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: print the OS family
  debug: msg="{{ ansible_os_family }}"

- name: Install Apache
  package:
    name: "{{ apache_package }}"
    state: present

- name: Copy web page
  copy:
    content: |
      <html>
      <head><title>Hello Molecules</title></head>
      <body>Hello little Molecules</body>
      </html>
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Start apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true